### ISSUE TITLE
[FEATURE REQUEST] Add an option to set a default value for image alignment

### ISSUE THREAD

**Issue by charmeee** [xRyul/obsidian-image-converter#127]
Hello! I love this great plugin. I always use drag resizing and right-click menu.

I was wondering if you could please add an option to set a default value for image alignment.
I usually use center align so i want to set default align to center.

**Comment by putizi-super** [comment]
+1

**Comment by samawelch** [comment]
I want to add that this can be (mostly) accomplished right now with a CSS snippet:

```css
/* align all images to the center */
img:not(.emoji) {
    display: block !important;
    margin-left: auto !important;
    margin-right: auto !important;
}

/* do the same to the image-resize-container that appears when you hover over an image with converter enabled */
.image-resize-container {
    display: block !important;
    margin-left: auto !important;
    margin-right: auto !important;
}
```

it's not as elegant a solution as the above would be, but it works, and it does still respect manually setting left/right alignment via the plugin. (adapted from [Cecilia May's snippet](https://forum.obsidian.md/t/how-to-center-an-image-automatically-with-minimal-theme-and-image-auto-upload-plugin/34683/4?u=tritici))
