### ISSUE TITLE
[BUG]: Custom image CSS tags get overwritten / removed when resizing

### ISSUE THREAD

**Issue by MaxWolf-01** [xRyul/obsidian-image-converter#44]
I have custom css tags for my images such as:
```css
img[alt*="center"] {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```
If I apply them to an image (`[image.png|center]`) and then resize with the image-converter resizing tool, they get removed. See the attached clip:
![Screencast from 2024-01-09 20:25:53.webm](https://github.com/xRyul/obsidian-image-converter/assets/69987866/eba9f2d2-f6eb-48b2-86fd-dcf2ab3bd4dc)

A _temporary_ workaround is to first resize and then center.
